theme: jekyll-theme-cayman
title: "The IHCC data harmonization project: Documentation and Instructions"
description: Documentation and Instructions for the  International HundredK+ Cohorts Consortium (IHCC) data harmonization project
